data_name: DBLP
workload: CLIQUE
N: 5
PT: 20
seed: 0
n_epoch: 400
ch_es: 100
rnn_hs: 256
pred_hs: 128
p_test: 0.1
p_val: 0.1
p_train: 1.0
n_pred_layer: 3
batch_size: 64
learning_rate: 1.0e-4
l2: 1.0e-6
patience: 20
packed: false
bound_in: true
pack_all: false
dynamicPT: true
max_entry_ratio: 3.12
ratio: 1.0
batch_norm: True
crh: True
tag: ""
