aggregation: pool
batch_size: 128
data_name: DBLP
workload: CLIQUE
learning_rate: 0.001
max_n_pat: 2
est_epoch: 256
p_test: 0.1
p_train: 1.0
p_val: 0.1
max_str_size: 5
emb_dim: 1024
emb_epoch: 32
emb_batch_size: 128
emb_lr: 0.001
est_scale: 8
seed: 0
patience: 20
packed: false
tag: ""