data_name: DBLP
workload: CLIQUE
min_count: 5
n_sample: 1000
wv_size: 500
n_epoch_wv: 30
n_epoch: 200
input_dim: 1000
hidden_dim: 256
hid_dim: 128
patience: 20
batch_size: 64
p_train: 1.0
p_valid: 0.1
p_test: 0.1
seed: 0
packed: false
lr: 0.001
tag: ''